version: '3.7'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: tfg_db
      POSTGRES_USER: acarriq
      POSTGRES_PASSWORD: 3432576
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  openvas:
    image: immauss/openvas
    container_name: openvas
    environment:
      - USER=admin
      - PASSWORD=admin
    ports:
      - "9392:9392"
    volumes:
      - openvas_data:/var/lib/openvas/mgr
    command: >
      /bin/bash -c "chown -R gvm:gvm /var/lib/openvas && chown -R gvm:gvm /var/lib/openvas/mgr && gvmd --listen=0.0.0.0 --port=9390"

volumes:
  postgres_data:
  es_data:
  openvas_data:
